[ansible]
src.vsmarketplace = "redhat.ansible"
fetch.vsmarketplace = "redhat.ansible"
passthru = { publisher = "redhat", name = "ansible" }

[biome]
src.vsmarketplace = "biomejs.biome"
fetch.vsmarketplace = "biomejs.biome"
passthru = { publisher = "biomejs", name = "biome" }

[chatgpt]
src.vsmarketplace = "openai.chatgpt"
fetch.vsmarketplace = "openai.chatgpt"
passthru = { publisher = "openai", name = "chatgpt" }

[claude-code]
src.vsmarketplace = "anthropic.claude-code"
fetch.vsmarketplace = "anthropic.claude-code"
passthru = { publisher = "anthropic", name = "claude-code" }

[copilot]
src.vsmarketplace = "github.copilot"
fetch.vsmarketplace = "github.copilot"
passthru = { publisher = "github", name = "copilot" }

[copilot-chat]
src.vsmarketplace = "github.copilot-chat"
fetch.vsmarketplace = "github.copilot-chat"
passthru = { publisher = "github", name = "copilot-chat" }

[explorer]
src.vsmarketplace = "vitest.explorer"
fetch.vsmarketplace = "vitest.explorer"
passthru = { publisher = "vitest", name = "explorer" }

[gemini-cli-vscode-ide-companion]
src.vsmarketplace = "Google.gemini-cli-vscode-ide-companion"
fetch.vsmarketplace = "Google.gemini-cli-vscode-ide-companion"
passthru = { publisher = "Google", name = "gemini-cli-vscode-ide-companion" }

[gopls]
src.github_tag = "golang/tools"
src.include_regex = "gopls/v[0-9]+\\.[0-9]+\\.[0-9]+"
fetch.github = "golang/tools"

[grafana-alloy]
src.vsmarketplace = "grafana.grafana-alloy"
fetch.vsmarketplace = "grafana.grafana-alloy"
passthru = { publisher = "grafana", name = "grafana-alloy" }

[grafana-vscode]
src.vsmarketplace = "grafana.grafana-vscode"
fetch.vsmarketplace = "grafana.grafana-vscode"
passthru = { publisher = "grafana", name = "grafana-vscode" }

[mypy-type-checker]
src.vsmarketplace = "ms-python.mypy-type-checker"
fetch.vsmarketplace = "ms-python.mypy-type-checker"
passthru = { publisher = "ms-python", name = "mypy-type-checker" }

[pdf]
src.vsmarketplace = "tomoki1207.pdf"
fetch.vsmarketplace = "tomoki1207.pdf"
passthru = { publisher = "tomoki1207", name = "pdf" }

[playwright]
src.vsmarketplace = "ms-playwright.playwright"
fetch.vsmarketplace = "ms-playwright.playwright"
passthru = { publisher = "ms-playwright", name = "playwright" }

[prom]
src.vsmarketplace = "ventura.prom"
fetch.vsmarketplace = "ventura.prom"
passthru = { publisher = "ventura", name = "prom" }

[pwc]
src.vsmarketplace = "SureshNettur.pwc"
fetch.vsmarketplace = "SureshNettur.pwc"
passthru = { publisher = "SureshNettur", name = "pwc" }

[pyrefly]
src.vsmarketplace = "meta.pyrefly"
fetch.vsmarketplace = "meta.pyrefly"
passthru = { publisher = "meta", name = "pyrefly" }

[remotehub]
src.vsmarketplace = "GitHub.remotehub"
fetch.vsmarketplace = "GitHub.remotehub"
passthru = { publisher = "GitHub", name = "remotehub" }

[ty]
src.vsmarketplace = "astral-sh.ty"
fetch.vsmarketplace = "astral-sh.ty"
passthru = { publisher = "astral-sh", name = "ty" }

[vscode-containers]
src.vsmarketplace = "ms-azuretools.vscode-containers"
fetch.vsmarketplace = "ms-azuretools.vscode-containers"
passthru = { publisher = "ms-azuretools", name = "vscode-containers" }

[vscode-gitops-tools]
src.vsmarketplace = "weaveworks.vscode-gitops-tools"
fetch.vsmarketplace = "weaveworks.vscode-gitops-tools"
passthru = { publisher = "weaveworks", name = "vscode-gitops-tools" }

[vscode-jsonnet]
src.vsmarketplace = "grafana.vscode-jsonnet"
fetch.vsmarketplace = "grafana.vscode-jsonnet"
passthru = { publisher = "grafana", name = "vscode-jsonnet" }

[vscode-pgsql]
src.vsmarketplace = "ms-ossdata.vscode-pgsql"
fetch.vsmarketplace = "ms-ossdata.vscode-pgsql"
passthru = { publisher = "ms-ossdata", name = "vscode-pgsql" }

[vscode-python-test-adapter]
src.vsmarketplace = "littlefoxteam.vscode-python-test-adapter"
fetch.vsmarketplace = "littlefoxteam.vscode-python-test-adapter"
passthru = { publisher = "littlefoxteam", name = "vscode-python-test-adapter" }

[vscode-thunder-client]
src.vsmarketplace = "rangav.vscode-thunder-client"
fetch.vsmarketplace = "rangav.vscode-thunder-client"
passthru = { publisher = "rangav", name = "vscode-thunder-client" }



